### ISSUE TITLE
Please consider add: MSG-Transformer: Exchanging Local Spatial Information by Manipulating Messenger Tokens (https://arxiv.org/abs/2105.15168)

### ISSUE THREAD

**Issue by Yuxin-CV** [dk-liang/Awesome-Visual-Transformer#16]
Thanks for your awesome repo.

Please consider add: MSG-Transformer: Exchanging Local Spatial Information by Manipulating Messenger Tokens (https://arxiv.org/abs/2105.15168).

**Comment by dk-liang** [comment]
Added
