### ISSUE TITLE
some papers to add

### ISSUE THREAD

**Issue by fawazsammani** [dk-liang/Awesome-Visual-Transformer#22]
- Escaping the Big Data Paradigm with Compact Transformers: https://arxiv.org/pdf/2104.05704.pdf
- How to train your ViT? Data, Augmentation,and Regularization in Vision Transformers: https://arxiv.org/pdf/2106.10270.pdf
- Beyond Self-attention: External Attention using Two Linear Layers for Visual Tasks: https://arxiv.org/pdf/2105.02358.pdf

**Comment by dk-liang** [comment]
added
