### ISSUE TITLE
add some papers

### ISSUE THREAD

**Issue by fawazsammani** [dk-liang/Awesome-Visual-Transformer#41]
hi, there are some recent papers i read, and they are missing from here:

TokenLearner: What Can 8 Learned Tokens Do for Images and Videos?
https://arxiv.org/pdf/2106.11297v2.pdf

Sliced Recursive Transformer
https://arxiv.org/pdf/2111.05297.pdf

**Comment by szq0214** [comment]
Hi @fawazsammani thanks so much for mentioning our paper :)

Hi @dk-liang thanks for collecting all of the vit papers which is definitely helpful, it will be greatly appreciated if you can also add Sliced Recursive Transformer in the list in case anyone is interested in it.
