### ISSUE TITLE
Add Augvit on NeurIPS 2021

### ISSUE THREAD

**Issue by yehuitang** [dk-liang/Awesome-Visual-Transformer#42]
Thanks for your awesome paper list !  Our paper 'Augmented Shortcuts for Vision Transformers' has accepted by NeurIPS 2021. Could you add it in the paper list? Thanks.

paper link: https://arxiv.org/abs/2106.15941

**Comment by yehuitang** [comment]
Thanks for your collection of these awesome papers. The code of Augvit has been released at https://github.com/huawei-noah/CV-Backbones/tree/master/augvit_pytorch. Thanks!

**Comment by dk-liang** [comment]
added
