### ISSUE TITLE
Add ICT

### ISSUE THREAD

**Issue by cddlyf** [dk-liang/Awesome-Visual-Transformer#50]
Hi, @dk-liang, please help add the below papers:

**[ICT]** High-Fidelity Pluralistic Image Completion with Transformers [[paper]](https://arxiv.org/pdf/2103.14031.pdf),  [[code]](https://github.com/raywzy/ICT), ICCV 2021

**[BEVT]** BEVT: BERT Pretraining of Video Transformers  [[paper]](https://arxiv.org/pdf/2112.01529.pdf),  [[code]](https://github.com/xyzforever/BEVT), CVPR 2022

**[PeCo]** PeCo: Perceptual Codebook for BERT Pre-training of Vision Transformers  [[paper]](https://arxiv.org/pdf/2111.12710.pdf)

**[MobileFormer]**  Mobile-Former: Bridging MobileNet and Transformer [[paper]](https://arxiv.org/pdf/2108.05895.pdf), CVPR 2022

**Comment by dk-liang** [comment]
added
