### ISSUE TITLE
Add VideoMAE

### ISSUE THREAD

**Issue by yztongzhan** [dk-liang/Awesome-Visual-Transformer#53]
VideoMAE: Masked Autoencoders are Data-Efficient Learners for Self-Supervised Video Pre-Training
paper: https://arxiv.org/abs/2203.12602
code: https://github.com/MCG-NJU/VideoMAE

**Comment by yztongzhan** [comment]
**[VideoMAE]** VideoMAE: Masked Autoencoders are Data-Efficient Learners for Self-Supervised Video Pre-Training [[paper](https://arxiv.org/abs/2203.12602)] [[code](https://github.com/MCG-NJU/VideoMAE)]

**Comment by yztongzhan** [comment]
Hi @dk-liang! Thanks for your nice repository. Could you add this paper?

**Comment by dk-liang** [comment]
added
