### ISSUE TITLE
Add BatchFormer

### ISSUE THREAD

**Issue by zhihou7** [dk-liang/Awesome-Visual-Transformer#59]
Hi @dk-liang, thanks for your awesome repository.
Could you add BatchFormer which has been accepted in CVPR2022.

arxiv: https://arxiv.org/abs/2203.01522
code: https://github.com/zhihou7/BatchFormer

In addition, a more general version, BatchFormerV2, is also released in https://arxiv.org/abs/2204.01254, in which we design a new module and present the consistent effectiveness on object detection, panoptic segmentation, and image classification.

Regards,

**Comment by dk-liang** [comment]
added
