### ISSUE TITLE
Add TransFusion (BMVC 2021)

### ISSUE THREAD

**Issue by HowieMa** [dk-liang/Awesome-Visual-Transformer#61]
Hi, @dk-liang, thanks for this great repository. Could you please consider adding TransFusion, which has been accepted in BMVC 2021? Thanks in advance! 

TransFusion: Cross-view Fusion with Transformer for 3D Human Pose Estimation
paper: https://arxiv.org/abs/2110.09554
code: https://github.com/HowieMa/TransFusion-Pose

**Comment by dk-liang** [comment]
added
