### ISSUE TITLE
Add HGOnet [WACV 2022]

### ISSUE THREAD

**Issue by kdh4672** [dk-liang/Awesome-Visual-Transformer#65]
Hi, @dk-liang, thanks for this great repository. Could you please consider adding HGOnet, which has been accepted in WACV 2022? Thanks in advance!

Image-Adaptive Hint Generation via Vision Transformer for Outpainting
paper: https://openaccess.thecvf.com/content/WACV2022/papers/Kong_Image-Adaptive_Hint_Generation_via_Vision_Transformer_for_Outpainting_WACV_2022_paper.pdf
code: https://github.com/kdh4672/hgonet

**Comment by dk-liang** [comment]
added
