### ISSUE TITLE
A kindly remind of the status of CrossFormer

### ISSUE THREAD

**Issue by cheerss** [dk-liang/Awesome-Visual-Transformer#77]
Thank you for your great project, and we are glad that our paper CrossFormer is also listed.

While our paper is listed as an arxiv pre-print, it has been accepted by ICLR 2022 [CrossFormer: A Versatile Vision Transformer Hinging on Cross-scale Attention](https://openreview.net/forum?id=_PHymLIxuI). You may wish to transfer it to the ICLR section.

**Comment by dk-liang** [comment]
added
