### ISSUE TITLE
Paper Status of P2T: Pyramid Pooling Transformer

### ISSUE THREAD

**Issue by yuhuan-wu** [dk-liang/Awesome-Visual-Transformer#78]
Dear Dingkang,

Thanks a lot for your project. Our paper P2T has been accepted by IEEE TPAMI 2022 recently.
Could you please update the status of P2T?
BTW, full code of P2T has also been released here: https://github.com/yuhuan-wu/P2T
IEEE online address is here: https://ieeexplore.ieee.org/document/9870559

Best,
Yu-Huan

**Comment by dk-liang** [comment]
added
